server:
  port: 9099
spring:
  jpa:
    show-sql: true
    hibernate: 
        ddl-auto: update
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
security:
  oauth2:
    resource:
      filter-order: 3
init-password: 123
test.key: wahaha
