server:
  port: 9099
spring:
  jpa:
    show-sql: true
    hibernate: 
        ddl-auto: update
  datasource:
      url: jdbc:mysql://120.78.214.165:3306/system_manager_clique?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Aliyung9b823ng*#
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maxLifetime: 1800000
        maximumPoolSize: 20
        connectionTimeout: 30000
        idleTimeout: 600000
        connection-test-query: SELECT 1
security:
  oauth2:
    resource:
      filter-order: 3
